### ISSUE TITLE
Handling of \"

### ISSUE THREAD

**Issue by z3str** [mtrberzi/z3#21]
(set-logic QF_S)
(set-info :status sat)
(declare-const str String)
(declare-const x String)
(declare-const var2 Int)
(declare-const var3 Int)

(assert (= x (CharAt "\"ello world!" 0) ) )

(check-sat)
(get-model)

**Comment by mtrberzi** [comment]
This is a Z3 bug, can you report this upstream to `Z3prover/Z3`? Thanks!
